version: '3.8'

services:
  symfony_app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "9999:9999"
    volumes:
      - ./api:/var/www/api
    develop:
      watch:
        - action: sync
          path: ./api
          target: /var/www/api
          ignore:
            - node_modules/
        - action: sync+restart
          path: ./api/composer.json
          target: /var/www/api/composer.json
        - action: sync
          path: ./api/src
          target: /var/www/api/src